project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://nmfs-ost.github.io/PAM_National_Network/" 
  repo-url: "https://github.com/nmfs-ost/PAM_National_Network"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/79/NOAA_logo.svg"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-ost.github.io/PAM_National_Network/
        text: "NMFS National Passive Acoustic Monitoring Network"
      - icon: github
        href: https://github.com/nmfs-ost/PAM_National_Network
        text: "NMFS PAM SI Lab Manual Github"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - section: content/SI coord/SI_Coordination.qmd
        text: PAM SI
        contents:
          - href: content/SI coord/PAM_priority_projects/PAM-Trends.qmd
            text: PAM-Trends
          - href: content/SI coord/PAM_priority_projects/PAM-OpenScience.qmd
            text: PAM-OpenScience
          - href: content/SI coord/PAM_priority_projects/PAM-Cloud.qmd
            text: PAM-Cloud
          - href: content/SI coord/PAM_priority_projects/PAM-Cloud-PACM.qmd
            text: PAM-Cloud-PACM
          - href: content/SI coord/PAM_priority_projects/PAM-Glider.qmd
            text: PAM-Glider
          - href: content/SI coord/PAM_priority_projects/PAM-NCEI.qmd
            text: PAM-NCEI
          - section: PAM Soundscape Projects
            contents:
             - href: content/SI coord/PAM_priority_projects/Soundscape_projects/Soundscape-Processing.qmd
               text: Processing and Archiving
             - href: content/SI coord/PAM_priority_projects/Soundscape_projects/Soundscape-Interpretation.qmd
               text: Interpretation and Visualization
          - section: PAM Stock Projects
            contents:
             - href: content/SI coord/PAM_priority_projects/Stock_projects/Project_1.qmd
               text: Glider tools
             - href: content/SI coord/PAM_priority_projects/Stock_projects/Project_2.qmd
               text: Stationary tools
      - href: content/FieldMethods.qmd
        text: "Field Methods"
      - href: content/DataManagement.qmd
        text: Data Management
      - href: content/Hardware.qmd
        text: Hardware
      - section: content/SoftwareAnalysis.qmd
#        text: "Software & Analysis"
        contents: 
          - content/Software.qmd
          - content/AnalysisMethods.qmd
      - href: content/Reporting.qmd
        text: Reporting
      - section: "Optional Pages"
        contents: 
          - content/SharedValues.qmd
          - content/Onboarding.qmd
          - content/Offboarding.qmd
          - content/FieldMethods.qmd
          - content/OpenScience.qmd
          - content/PublicationsPresentations.qmd
          - content/Resources.qmd
      # - section: "NMFS Open Science Directions"  #Removed but did not yet delete
      #   contents:
      #     - content/NMFS_OpenSciDirections/Getting-Started.qmd
      #     - content/NMFS_OpenSciDirections/organize.qmd
      #     - content/NMFS_OpenSciDirections/add-content.qmd
      #     - content/NMFS_OpenSciDirections/rendering.qmd
      #     - content/NMFS_OpenSciDirections/rmarkdown.Rmd
      #     - content/NMFS_OpenSciDirections/code.qmd
      #     - content/NMFS_OpenSciDirections/acknowledgements.qmd 
        
format:
  html:
    link-external-icon: false
    link-external-newwindow: true
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
