---
title: "PAM-Soundscapes"
subtitle: "Soundscape Analysis, Metrics, & Tools"
page-layout: full
---


## Project 2: Soundscape Metric Interpretation and Visualization

### Goal and Target Outcome

We will create a set of soundscape metric interpretation open-source processing pathways and visualizations for cross-FMCs comparisons and FMCs-specific soundscape priorities.

### Summary

This project will build on existing tools in PAMscapes (R/CRAN) to create and document processing pathways for soundscape metric interpretation. NOAA Noise Reference Station soundscape metrics will be used to build the pathways and evaluate outputs. Additional soundscape metrics from PAM SI priority data sets will be incorporated based on availability from Soundscape Priority #1 Projects (above). We will create decision-support tools that are relevant at regional and national scales and integrate PAM data with variables to provide context for different soundscapes (environmental data, species-detections, etc).