---
title: Project 2 - Incorporating stationary data into a species distribution modeling framework
---

### Team leads
Lance Garrison (SEFSC), Melissa Soldevilla (SEFSC), Ann Allen (PIFSC), Genevieve Davis (NEFSC), Manolo Castellote (AFSC), Marla Holt (NWFSC), Jason Gedamke (OST)

### Target outcome:
Integrating long-term PAM data into species density models to provide seasonal and long-term changes in distribution and density.

### Summary
This project would support the PAM SI objective of advancing data integration by leveraging stationary PAM data and visual data to improve the accuracy of stock assessments by capturing seasonal and long-term changes. This project would focus on developing a statistical framework for integrating a density model created with stationary PAM data with existing visual-based SDMs to achieve more accurate models with seasonal context. This project may leverage LISTEN GoMex funding to develop models for sperm whales and
beaked whales.

### Action items
1. **Establish collaboration:** Meet with Lance Garrison to identify his interest and willingness to convene a working group to support his ongoing effort and work towards broader applicability of the outcomes.

2. **Identify resources required:** Evaluate whether LISTEN GoMex requires more resources to make these methods broadly applicable.

3. **Confer with PAM SI Working Group:** Working Group determines whether there is substantial interest and priority for continued pursuit of this project. If no-go, determine whether the project may be re-evaluated later based on funds available. Deadline: May 2024. Note: As of May 2024, this project was not selected for funding by the PAM SI Working Group. However, given the synergies between integrating stationary PAM data and mobile PAM data, the SI will leverage any PAM data integration workshops held to assess the state of the science for integrating both data types into species distribution modeling framework. This will advance our analytical readiness to pursue this project at a later time.

4. **Establish project team:** Establish working group, potentially including colleagues from Duke University, Fisheries and Oceans Canada, etc., to meet periodically with the LISTEN GoMex team to ensure broad regional relevance. 

5. **Expand capacity:** If funded, advertise post-doc position to support this effort. Alterntively, the PAM SI could convene a workshop or series of workshops that assess the state of the science for incorporating PAM data into species distribution model frameworks in conjunction with Project 1. 