---
title: "Meetings"
format: html
---

Important links to meeting documents :

- [Notes from Bi-weekly SI Team Meetings](https://docs.google.com/document/d/1S1hxuyJ1MenSJsAr4ZSEihF6L58rrkmP52a3_fN3FIk/edit?usp=drive_link)

- PAM-SI Virtual Meeting September 2026

  - [**Agenda**](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/PAM-SI-Virtual-Workshop-Agenda_%20Sept-2026.pdf)
  - [**Meeting Report**](https://github.com/nmfs-ost/PAM_National_Network/tree/main/content/SI%20coord/supplement/PAM-SI_VirtualWorkshop_2026_Report.pdf)
  - **Thursday Presentations:** **PAM Analytical Developments**
    - [Spacious: Integrating slow-moving PAM platforms into species distribution models](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/SPACIOUS-2026-September-Status-Update.pdf)
    - [East Coast DASBRs: Expanding acoustic density estimation](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/DeAngelis_EC-Drifters_PAM-SI_20260924.pdf)
    - [Gulf LISTEN: Linking ocean dynamics to cetacean distributions](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/Solsona-Berga_LISTEN_HabitatModeling_PAM-SI_20260924.pdf)
    - [PAM Applications for fisheries management and stock assessments (SARS)](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/Mouy_VanHoeck_Fish_PAM-SI-Workshop_2026-09-24.pdf)
    - [U.S. Ocean Soundscape monitoring & condition reporting](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/SoundscapeMonitoring.us-overview-for-PAM-SI.pdf),
    - [PAMverse RStudio Ecosystem: Data integration & environmental matching](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/PAMverse-Update-20260924.pdf)
    - [Makara Database, PACM, and PARS Data Ecosystem](https://github.com/nmfs-ost/PAM_National_Network/blob/main/content/SI%20coord/supplement/Makara-and-PACM-PAM-SI-Workshop-20260924.pdf)
  - **Friday Presentations:** **National PAM Cloud Work**
    - [National PAM Cloud overview & modernized batch workflows](https://nmfs-ost.github.io/PAM_National_Network/content/SI%20coord/supplement/Cloud-Overview-Processing_PAM-SI-Virtual-Workshop-Sept-2026.pdf)
    - [NCEI Archiving Pipeline & Tugboat](https://nmfs-ost.github.io/PAM_National_Network/content/SI%20coord/supplement/NCEI-NMFS-Tugboat_PAM-SI_Sept-25.pdf)
    - [Cloud Storage Architecture, Ingest, and Cost Optimization](https://nmfs-ost.github.io/PAM_National_Network/content/SI%20coord/supplement/Dan-Woodrich-Cloud-storage.pdf)
    - [Cloud-based Navy Review & Data handling protocols](https://nmfs-ost.github.io/PAM_National_Network/content/SI%20coord/supplement/Gedamke_PAM-SI-Meeting-Sept-2026.pdf)
    - [Cloud Windows Workstation (pam-ww)](Dan-Woodrich-PAM-Windows-workstations)
    - Batch-Scale processing \[live demos, no slides\]
    - [Annotation to AI Classification (Perch/Hoplite)](https://nmfs-ost.github.io/PAM_National_Network/content/SI%20coord/supplement/Ann%20Allen_PerchHoplitePresentation.pdf)

- [March 2024 Workshop Report](https://drive.google.com/file/d/1YJsUSxBJ0xDJAtz9DfxAc1tO-cmyBExG/view?usp=drive_link)
